apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  CLICKHOUSE_URL: "jdbc:mysql://clickhouse:9004/default"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_PASSWORD: "password"
