apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: envoy
    descriptors:
      - key: generic_key
        value: write_api
        rate_limit:
          requests_per_unit: 500
          unit: second
    ---
    domain: envoy-read
    descriptors:
      - key: generic_key
        value: read_api
        rate_limit:
          requests_per_unit: 5000
          unit: second
